--create database Active_Finance

 --use Active_Finance

--CREATE TABLE [ACTIVE_FINANCE].[DBO].[EXTRACOESFUNDOIMOBILIARIO]
--(
--	ID INT PRIMARY KEY IDENTITY(1,1),
--	LASTINSERTION DATETIME DEFAULT GETDATE(),
--	VALORATUAL FLOAT,
--	MIN52SEMANAS FLOAT,
--	MAX52SEMANAS FLOAT,
--	DIVIDENDYELD FLOAT,
--	VALORIZACAO12MESES FLOAT,
--	VALPATRIMONIALPORCOTA FLOAT,
--	PVP FLOAT, 
--	VALOREMCAIXA FLOAT,
--	ULTIMORENDIMENTO FLOAT,
--	RENDIMENTO FLOAT,
--	COTACAOBASE FLOAT,
--	[DATABASE] DATETIME,
--	DATAPAGAMENTO DATETIME
--)

select * from [ACTIVE_FINANCE].[DBO].[EXTRACOESFUNDOIMOBILIARIO]

--CREATE TABLE [ACTIVE_FINANCE].[DBO].[EXTRACOESACOES]
--(
--	ID INT PRIMARY KEY IDENTITY(1,1),
--	LASTINSERTION DATETIME DEFAULT GETDATE(),
--	VALORATUAL FLOAT,
--	MIN52SEMANAS FLOAT,
--	MAX52SEMANAS FLOAT,
--	DIVIDENDYELD FLOAT,
--	VALORIZACAO12MESES FLOAT, 
--	PRECOLUCRO FLOAT,
--	PRECOSOBREVALORPATRIMONIAL FLOAT,
--	VALORPATRIMONIALPORACAO FLOAT, 
--	LUCROPORACAO FLOAT,
--	DIVIDALIQUIDAPORPATRIMONIOLIQUIDO FLOAT,
--	MARGEMBRUTA FLOAT,
--	RETORNOSOBREPATRIMONIOLIQUIDO FLOAT,
--)

SELECT * FROM [ACTIVE_FINANCE].[DBO].[EXTRACOESACOES]
